export {default as Enquire} from "./Enquire/Enquire"
export {default as Gallery} from "./Gallery/Gallery"
export {default as HomePage} from "./HomePage/HomePage"
export {default as Login} from "./Login/Login"
export {default as Service} from "./Service/Service"
export {default as Signin} from "./Signin/Signin"
export {default as SplashScreen} from "./SplashScreen/SplashScreen"
export {vendors,topVendors} from "./Vendores/Vendors"
export {default as VendorsPage} from "./VendorPage/VendorPage"